#!/usr/bin/python3
# Created by: BizHat

import os
import re
import subprocess


rs_worlds_all = (
    1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,
    18,19,20,21,22,23,24,25,26,27,28,29,30,31,
    32,33,34,35,36,37,38,39,40,41,42,43,44,45,
    46,47,48,49,50,51,52,53,54,55,56,57,58,59,
    60,61,62,63,64,65,66,67,68,69,70,71,72,73,
    74,75,76,77,78,79,80,81,82,83,84,85,86,87,
    88,89,91,92,94,96,97,98,99,100,101,
    102,103,104,105,106,108,111,114,115,
    116,117,118,119,120,121,122,123,124,
    134,135,136,137,138,139,140
)

server_ping = dict()

def ping(hostname):
    try:
        output = subprocess.check_output("ping -c 2 " + hostname, shell=True)
    except:
        return 0
    r = re.compile('rtt min/avg/max/mdev = [\d\.]*/([\d]*)\.')
    f = r.findall(output.decode("utf-8"))
    return int(f[0])

if __name__ == "__main__":

    #ping(server)
    for rs_world_number in rs_worlds_all:
        rs_server = 'world' + str(rs_world_number) + '.runescape.com'
        ping_result = ping(rs_server)
        if ping_result > 0:
            server_ping[rs_server] = ping_result

    server_ping_sorted = sorted(server_ping.items(), key=lambda x:x[1], reverse=True)

    for world in server_ping_sorted:
        print(world[0] + "\t" + str(world[1]))
