#!/bin/bash

if [ $# -eq 0 ]; then
    echo Usage: pingw world_number
    exit 1
fi

if [[ "$1" =~ ^[0-9]+$ ]];
then
    ping -c 5 world$1.runescape.com
else
    echo "Input must be a number";
    exit 1
fi

