#!/bin/bash

VMNAME=$1

MAC=$(virsh dumpxml ${VMNAME} | awk -F\' '/mac address/ {print $2}')

while true
do
    if [ -f /var/lib/libvirt/dnsmasq/default.leases ]; then
       IP=$(grep -B1 $MAC /var/lib/libvirt/dnsmasq/default.leases | \
          head -n 1 | awk '{print $3}' | sed -e s/\"//g -e s/,//)
    else
        IP=$(virsh net-dhcp-leases default | grep $MAC | awk '{print $5}' | awk -F "/" '{print $1}')
    fi

    if [ "$IP" = "" ]
    then
        sleep 1
    else
        break
    fi
done

echo $IP
