#!/bin/bash

VMNAME=$1

virsh dumpxml ${VMNAME} > /dev/null 2>&1

if [ "$?" -ne 0 ]
then
    echo "VM not found: ${VMNAME}"
    exit 1
fi

echo "virsh destroy ${VMNAME}"
virsh destroy ${VMNAME}

echo "virsh pool-destroy ${VMNAME}"
virsh pool-destroy ${VMNAME}

echo "virsh pool-undefine ${VMNAME}"
virsh pool-undefine ${VMNAME}

echo "virsh undefine ${VMNAME}"
virsh undefine ${VMNAME}

if [ "$(id -u)" -eq 0 ]
then
    rm -f /home/virt/vm/${VMNAME}/*
    rmdir /home/virt/vm/${VMNAME}/
else
    rm -f $HOME/virt/vm/${VMNAME}/*
    rmdir $HOME/virt/vm/${VMNAME}/
fi

echo "Virtual Machine deleted: ${VMNAME}"
