#!/bin/bash

VMNAME=$1

virsh dumpxml ${VMNAME} > /dev/null 2>&1

if [ "$?" -ne 0 ]
then
    echo "VM not found: ${VMNAME}"
    exit 1
fi

set -x

virsh destroy ${VMNAME}

virsh pool-destroy ${VMNAME}

virsh pool-undefine ${VMNAME}

virsh undefine ${VMNAME}

set +x

if [ "$(id -u)" -eq 0 ]
then
    set -x
    rm -f /home/virt/vm/${VMNAME}/*
    rmdir /home/virt/vm/${VMNAME}/
    set +x
else
    set -x
    rm -f $HOME/virt/vm/${VMNAME}/*
    rmdir $HOME/virt/vm/${VMNAME}/
    set +x
fi


echo "Virtual Machine deleted: ${VMNAME}"
